Repository openapi-env-test/azure-rest-api-specs, pull requests merged in 2021-04, with the labels that each got.

#2635 Update 1
  specification/cdn/resource-manager/Microsoft.Cdn/stable/2020-09-01/cdn.json
Labels: CI-BreakingChange-Go

#2639 Update 2
  specification/cdn/resource-manager/Microsoft.Cdn/stable/2020-09-01/cdn.json
Labels: Approved-BreakingChange, BreakingChangeReviewRequired, CI-BreakingChange-Go

#2643 Update ManagedIdentity.json
  specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2018-11-30/ManagedIdentity.json
Labels: BreakingChangeReviewRequired, CI-BreakingChange-Go

#2636 Update with BreakingChange
  specification/cdn/resource-manager/Microsoft.Cdn/stable/2020-09-01/cdn.json
Labels: Approved-BreakingChange, Approved-SdkBreakingChange-Go, Approved-SdkBreakingChange-Python, BreakingChangeReviewRequired, CI-BreakingChange-Go, CI-BreakingChange-Python-Track2

#2763 Update ManagedIdentity.json
  specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2018-11-30/ManagedIdentity.json
Labels: CI-BreakingChange-Go
